
export const LOGIN_NAME = 'LOGIN_NAME'
export const LOGIN_NAME_REQUEST = 'LOGIN_NAME_REQUEST'
export const LOGOUT_NAME  = 'LOGOUT_NAME'
export const RENEW_NAME  = 'RENEW_NAME'
export const USER_NAME_FAIL = 'USER_NAME_FAIL'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER = 'GET_USER'
export const GET_USER_FAIL = 'GET_USER_FAIL'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS = 'GET_USERS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'

export const GET_USERS_BY_CHAT_REQUEST = 'GET_USERS_BY_CHAT_REQUEST'
export const GET_USERS_BY_CHAT = 'GET_USERS_BY_CHAT'
export const GET_USERS_BY_CHAT_FAIL = 'GET_USERS_BY_CHAT_FAIL'